namespace:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUser: |
    - userarn:  <>
      username: debain12_user
      group:
        - system:master
